#name Gun ho Park 
#id gp3dz
#lab 102

CXX=clang++ $(CXXFLAGS)
DEBUG=-Wall -g

OFILES = pizza.o pizzadough.o tomatosauce.o toppings.o mushrooms.o peppers.o cheese.o pepperoni.o
CXXFLAGS = -Wall -g

pizza: $(OFILES)
	$(CXX) $(CXXFLAGS) $(DEBUG) $(OFILES) -o pizza
	@echo "Pizza is Hot and Ready!"
	
pizza.o: pizza.cpp
	$(CXX) -c pizza.cpp

pizzadough.o: pizzadough.cpp pizzadough.h
	$(CXX) -c pizzadough.cpp
	
tomatosauce.o: tomatosauce.cpp tomatosauce.h
	$(CXX) -c tomatosauce.cpp
	
toppings.o: pepperoni.cpp peppers.cpp mushrooms.cpp cheese.cpp toppings.cpp \
			pepperoni.h peppers.h mushrooms.h cheese.h toppings.h
	$(CXX) -c toppings.cpp
	
pepperoni.o: pepperoni.cpp pepperoni.h
	$(CXX) -c pepperoni.cpp
	
mushrooms.o: mushrooms.cpp mushrooms.h
	$(CXX) -c mushrooms.cpp
	
peppers.o: peppers.cpp peppers.h
	$(CXX) -c peppers.cpp

cheese.o: cheese.cpp cheese.h
	$(CXX) -c cheese.cpp
	
	
clean:
	-rm -f *.o *.~ pizza

cheese.o: cheese.cpp cheese.h
mushrooms.o: mushrooms.cpp mushrooms.h
pepperoni.o: pepperoni.cpp pepperoni.h
peppers.o: peppers.cpp peppers.h
pizza.o: pizza.cpp pizzadough.h tomatosauce.h toppings.h cheese.h \
  mushrooms.h peppers.h pepperoni.h
pizzadough.o: pizzadough.cpp pizzadough.h
tomatosauce.o: tomatosauce.cpp tomatosauce.h
toppings.o: toppings.cpp toppings.h cheese.h mushrooms.h peppers.h \
  pepperoni.h

